(ns mytrade.core
  (:require
   [reagent.core :as reagent :refer [atom]]
   [reagent.dom :as rdom]
   [reagent.session :as session]
   [cljs.core.async :as async :refer [go <!]]
   [reitit.frontend :as reitit]
   [mytrade.charts :refer [stock]]
   [mytrade.data :as data]
   [clerk.core :as clerk]
   [accountant.core :as accountant]))

;; -------------------------
;; Routes

(def router
  (reitit/router
   [["/" :index]
    ["/items"
     ["" :items]
     ["/:item-id" :item]]
    ["/about" :about]]))

(defn path-for [route & [params]]
  (if params
    (:path (reitit/match-by-name router route params))
    (:path (reitit/match-by-name router route))))

;; -------------------------
;; Page components

(defn home-page []
  (fn []
    [:span.main
     [:h1 "Welcome to vtrade"]
     [:ul
      [:li [:a {:href (path-for :items)} "Items of vtrade"]]
      [:li [:a {:href "/broken/link"} "Broken link"]]]]))


(def data (atom []))
(defn pingan-chart
  [{:keys [Data_ACWorthTrend
           Data_grandTotal
           managers]}]
  [stock
   {:chart-data {:rangeSelector {:selected 5},
                 :title {:text "平安银行历史股价"},
                 :plotOptions {:series {:showInLegend true}},
                 :tooltip {:split false, :shared true},
                 :series [{:id "000001",
                           :name "470009",
                           :data @data}
                          ]}}])

(defn items-page []
  (fn []
    [:div.columns
     [:div.column
      [pingan-chart]]
    ]))


(defn item-page []
  (fn []
    (let [routing-data (session/get :route)
          item (get-in routing-data [:route-params :item-id])]
      [:span.main
       [:h1 (str "Item " item " of vtrade")]
       [:p [:a {:href (path-for :items)} "Back to the list of items"]]])))


(defn about-page []
  (fn [] [:span.main
          [:h1 "About vtrade"]]))


;; -------------------------
;; Translate routes -> page components

(defn page-for [route]
  (case route
    :index #'home-page
    :about #'about-page
    :items #'items-page
    :item #'item-page))


;; -------------------------
;; Page mounting component

(defn current-page []
  (fn []
    (let [page (:current-page (session/get :route))]
      [:div
       [:header
        [:p [:a {:href (path-for :index)} "Home"] " | "
         [:a {:href (path-for :about)} "About vtrade"]]]
       [page]
       [:footer
        [:p "vtrade was generated by the "
         [:a {:href "https://github.com/reagent-project/reagent-template"} "Reagent Template"] "."]]])))

;; -------------------------
;; Initialize app

(defn mount-root []
  (rdom/render [current-page] (.getElementById js/document "app")))

(defn init []
  (clerk/initialize!)
  (accountant/configure-navigation!
   {:nav-handler
    (fn [path]
      (let [match (reitit/match-by-path router path)
            current-page (:name (:data  match))
            route-params (:path-params match)]
        (reagent/after-render clerk/after-render!)
        (session/put! :route {:current-page (page-for current-page)
                              :route-params route-params})
        (clerk/navigate-page! path)
        ))
    :path-exists?
    (fn [path]
      (boolean (reitit/match-by-path router path)))})
  (accountant/dispatch-current!)
  (mount-root)
  (go (->> (<! (data/get-fund "470009")) :Data_ACWorthTrend (reset! data )))
  )
